version: 0.2
phases:
  install:
    # Latest Runtime Version 16.x On May 2022
    runtime-versions:
      nodejs: 16
    commands:
      # Install chrome
      - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
      - apt-get update && apt-get install -y google-chrome-stable
      # Package Installation for Application and Deployment Scripts
      - echo Installation Process Started
      - npm install
  pre_build:
    commands:
      # Linting & Testing
      - echo Linting Process Started
      - npm run lint
      - echo Testing Process Started
      - npm run test
      - echo Build Process Started
      - npm run build
